export const ACTIVITY_ACTIONS = {
  LOGIN: 'LOGIN',
  TEST_SUBMIT: 'TEST_SUBMIT',
  PRACTICE_SUBMIT: 'PRACTICE_SUBMIT',
  MISSION_COMPLETE: 'MISSION_COMPLETE',
  TEST_DEPLOY: 'TEST_DEPLOY',
  TEST_GRADE: 'TEST_GRADE',
  ACADEMY_SETTINGS_UPDATE: 'ACADEMY_SETTINGS_UPDATE',
  // 학생
  LEVEL_TEST_COMPLETE: 'LEVEL_TEST_COMPLETE',
  WORD_STUDY: 'WORD_STUDY',
  WORD_REVIEW_COMPLETE: 'WORD_REVIEW_COMPLETE',
  WORD_TEST_SUBMIT: 'WORD_TEST_SUBMIT',
  // 교사/학원장
  WORD_TEST_ASSIGN: 'WORD_TEST_ASSIGN',
  WORD_SET_CREATE: 'WORD_SET_CREATE',
  LEVEL_OVERRIDE: 'LEVEL_OVERRIDE',
  ATTENDANCE_SESSION_END: 'ATTENDANCE_SESSION_END',
} as const

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[keyof typeof ACTIVITY_ACTIONS]

export const ACTIVITY_ACTION_LABELS: Record<string, string> = {
  LOGIN: '로그인',
  TEST_SUBMIT: '테스트 제출',
  PRACTICE_SUBMIT: '연습문제 제출',
  MISSION_COMPLETE: '오늘의 미션 완료',
  TEST_DEPLOY: '테스트 출제',
  TEST_GRADE: '채점 완료',
  ACADEMY_SETTINGS_UPDATE: '학원 설정 변경',
  LEVEL_TEST_COMPLETE: '레벨 테스트 완료',
  WORD_STUDY: '단어학습',
  WORD_REVIEW_COMPLETE: '단어 복습 완료',
  WORD_TEST_SUBMIT: '단어시험 제출',
  WORD_TEST_ASSIGN: '단어시험 출제',
  WORD_SET_CREATE: '단어세트 생성',
  LEVEL_OVERRIDE: '레벨 수동 조정',
  ATTENDANCE_SESSION_END: '출결 마감',
}
