import { config } from 'dotenv'
config({ path: '.env.local' })

import { PrismaClient, QuestionDomain, QuestionSource } from '../src/generated/prisma'

const prisma = new PrismaClient()

const SOURCE_LABEL =
  '출처: 2026학년도 대학수학능력시험 영어 영역 유형 참조 유사문제 (18-45번, 저작권 보호를 위해 유사문제로 재구성)'

// ─── 장문 공유 지문 1 (41·42번) ───────────────────────────────────────────
const LONG_PASSAGE_1 = `The concept of "informational autonomy" — the right of individuals to control the data generated by their own behavior — has become increasingly central to debates about digital privacy. In the early years of the internet, data was largely understood as a byproduct of activity, a technical trace with little intrinsic value. As analytical techniques matured and the commercial potential of behavioral data became clear, that view changed dramatically. Today, every search query, purchase, location ping, and social interaction feeds into profiles of extraordinary granularity. These profiles enable targeted advertising with uncanny precision, but they also make possible more troubling applications: dynamic pricing that charges individuals different rates based on predicted willingness to pay, insurance algorithms that infer health risk from lifestyle data, and political micro-targeting that delivers individualized messages calibrated to specific psychological vulnerabilities.

Defenders of these practices argue that users consent to data collection through terms of service agreements, and that the benefits — free services, personalized experiences, relevant advertising — represent fair compensation. Critics respond that such consent is largely fictional: agreements run to thousands of words in legal language few users read, and the alternative to acceptance is exclusion from platforms that have become essential infrastructure. More fundamentally, critics argue, the power asymmetry between individuals and data-holding institutions is so extreme that meaningful autonomy is structurally impossible without legal intervention.`

// 42번용: (a)~(e) 표시 버전
const LONG_PASSAGE_1_ANNOTATED = `The concept of "informational autonomy" — the right of individuals to control the data generated by their own behavior — has become increasingly central to debates about digital privacy. In the early years of the internet, data was largely understood as a (a)byproduct of activity, a technical trace with little intrinsic value. As analytical techniques matured and the commercial potential of behavioral data became clear, that view changed (b)dramatically. Today, every search query, purchase, location ping, and social interaction feeds into profiles of extraordinary (c)granularity. These profiles enable targeted advertising with (d)uncanny precision, but they also make possible more troubling applications: dynamic pricing that charges individuals different rates based on predicted willingness to pay, insurance algorithms that infer health risk from lifestyle data, and political micro-targeting that delivers individualized messages calibrated to specific psychological (e)strengths.

Defenders of these practices argue that users consent to data collection through terms of service agreements, and that the benefits — free services, personalized experiences, relevant advertising — represent fair compensation. Critics respond that such consent is largely fictional: agreements run to thousands of words in legal language few users read, and the alternative to acceptance is exclusion from platforms that have become essential infrastructure. More fundamentally, critics argue, the power asymmetry between individuals and data-holding institutions is so extreme that meaningful autonomy is structurally impossible without legal intervention.`

// ─── 장문 공유 지문 2 (43·44·45번) ──────────────────────────────────────────
const LONG_PASSAGE_2 = `(A) Every summer, Dr. Nora Shin returned to the same coastal village where she had grown up, not to rest, but to run a free health clinic for the elderly residents who had no other access to medical care. On her first visit back after completing her residency, she arrived to find the community center where she had always set up her equipment locked and abandoned.

(B) After asking around, she learned that the center had been closed following a dispute between local families over a donation. Nobody could agree on how the money should be spent, and in the resulting standoff, the building had simply been left to deteriorate. Nora felt a wave of frustration. She had driven four hours and turned down a lucrative conference invitation to be here.

(C) That evening, she knocked on the door of old Mr. Yoon, whose family had been at the center of the disagreement. He answered warily, but when she explained that patients were going without blood pressure checks and diabetes screenings because of the locked building, something in his expression changed. He made a phone call. By morning, the center was open.

(D) As she set up her equipment, Nora noticed that the families who had been feuding were working alongside each other, arranging chairs and carrying supplies. Nobody mentioned the argument. Whatever Mr. Yoon had said the night before, it had been enough. She began to understand that what communities sometimes need most is not a mediator or a policy, but a concrete reminder of what they stand to lose.`

const questions = [
  // ─── 18번 글의 목적 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '글의 목적',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 18,
    passage: `Dear Ms. Harper,

I am writing on behalf of the students in the Advanced Science Club at Westfield High School. We have been following the research your laboratory has published on renewable energy storage, and we are truly inspired by your work. Our club is planning a semester-long project on sustainable energy solutions, and we would be honored if you could visit our school and speak to us about your journey and findings. A one-hour session would give us the opportunity to ask questions and gain insight that no textbook can offer. We understand that your schedule may be demanding, and we are flexible with timing. Please let us know if this is something you would consider. We believe your visit would be a turning point for many of our students.

Sincerely,
Daniel Cho
President, Advanced Science Club`,
    question: '다음 글의 목적으로 가장 적절한 것은?',
    options: [
      '연구비 지원을 요청하려고',
      '과학 실험 결과를 보고하려고',
      '방문 강연을 부탁하려고',
      '학교 행사에 후원을 요청하려고',
      '연구소 견학 일정을 확인하려고',
    ],
    answer: 3,
    explanation: `편지의 핵심 문장은 "we would be honored if you could visit our school and speak to us"이다. 필자는 과학 클럽 학생들을 위해 강연자 방문을 요청하고 있으므로 정답은 ③이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 19번 심경 변화 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '심경 변화',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 19,
    passage: `The stage lights blinded Mia as she walked on. She had rehearsed this piano piece a hundred times, yet her fingers felt like stone. The audience, a sea of unfamiliar faces, seemed to lean forward in expectation. Her heart hammered. She sat down, placed her hands on the keys, and froze. The opening chord refused to come. Then, from somewhere in the third row, she heard a soft cough — the same nervous cough her grandfather always made when he was rooting for her. She looked up and found him in the crowd, nodding slowly, his eyes full of warmth. Something unlocked inside her. She turned back to the keys and began to play, and as the notes filled the hall, she felt herself lifted by them, carried forward, no longer afraid.`,
    question: '다음 글에 드러난 Mia의 심경 변화로 가장 적절한 것은?',
    options: [
      'nervous → relieved',
      'bored → excited',
      'confident → embarrassed',
      'indifferent → grateful',
      'anxious → delighted',
    ],
    answer: 5,
    explanation: `처음 Mia는 무대에서 극도로 긴장("her fingers felt like stone", "Her heart hammered")하다가 할아버지를 발견한 후 두려움이 사라지고 기쁘게 연주한다("no longer afraid"). 따라서 심경 변화는 ⑤ anxious → delighted이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 20번 필자 주장 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '필자 주장',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 20,
    passage: `Many educators celebrate technology as the solution to every classroom problem. Interactive screens, AI tutors, and gamified apps dominate the conversation about modern learning. Yet we rarely ask whether students are becoming more capable thinkers, or simply more practiced consumers of digital content. Research consistently shows that reading long-form printed texts develops sustained attention, analytical depth, and the ability to hold complex ideas in mind simultaneously — skills that fragmented digital reading struggles to build. Rather than replacing books with screens, schools should protect extended reading time as a non-negotiable element of the curriculum. Teaching students to sit with difficulty, to wrestle with a dense paragraph until it yields meaning, is not an outdated practice — it is the foundation of genuine intellectual development.`,
    question: '다음 글에서 필자가 주장하는 바로 가장 적절한 것은?',
    options: [
      '디지털 학습 도구의 교육적 효과를 검증해야 한다.',
      '교사는 기술 활용 역량을 꾸준히 향상시켜야 한다.',
      '학교는 긴 글 읽기 시간을 교육과정에서 반드시 보호해야 한다.',
      '학생들이 스스로 학습 목표를 설정하도록 지도해야 한다.',
      '독서 습관 형성을 위해 가정에서의 지원이 중요하다.',
    ],
    answer: 3,
    explanation: `필자는 "schools should protect extended reading time as a non-negotiable element of the curriculum"이라고 명시적으로 주장한다. 따라서 정답은 ③이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 21번 밑줄 의미 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '밑줄 의미',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 21,
    passage: `Urban planners once believed that a city, once designed, would settle into a stable shape — a fixed network of roads, zones, and functions that residents would simply inhabit. But decades of observation have forced a more humble view. Cities are not finished products. They are organisms shaped by waves of migration, economic shifts, political decisions, and the accumulated desires of millions of individual people. A neighborhood that housed factories fifty years ago may now be filled with galleries and coffee shops; a suburb that was wealthy a generation ago may now be struggling. Planners who try to work from yesterday's assumptions quickly find that the map keeps redrawing itself, and the only competence that truly matters is the ability to read movement rather than static form.`,
    question: '밑줄 친 "the map keeps redrawing itself"가 다음 글에서 의미하는 바로 가장 적절한 것은?',
    underline: 'the map keeps redrawing itself',
    options: [
      '도시 계획이 반복적으로 수정되어야 한다',
      '도시의 구조와 특성이 끊임없이 변화한다',
      '지도 제작 기술이 빠르게 발전하고 있다',
      '주민들의 이동 경로를 정확히 추적해야 한다',
      '도시 계획가가 새로운 지도 읽기 방식을 배워야 한다',
    ],
    answer: 2,
    explanation: `"the map keeps redrawing itself"는 직전 예시들(공장→갤러리, 부촌→빈곤지역)에서 보듯이 도시의 구조와 특성이 끊임없이 변한다는 것을 비유적으로 표현한 것이다. 정답은 ②이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 22번 글의 요지 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '글의 요지',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 22,
    passage: `When we talk about creativity, we tend to imagine solitary geniuses producing ideas from nothing. But this picture is largely a myth. Almost every creative breakthrough in history can be traced to a web of conversations, collaborations, and borrowed concepts. Darwin's theory of natural selection emerged partly from reading Malthus; Edison's lightbulb was the product of a large team of engineers; even Shakespeare drew heavily on earlier sources. Creativity is less about generating something from thin air and more about recombining existing elements in ways that feel new. This does not diminish the achievement — recombination requires sensitivity, judgment, and originality of vision. But it does suggest that the best environment for creativity is not isolation, but a rich network of diverse people and ideas.`,
    question: '다음 글의 요지로 가장 적절한 것은?',
    options: [
      '창의적 사고는 반복적인 훈련을 통해 향상된다.',
      '창의성은 고립보다 다양한 교류와 조합에서 비롯된다.',
      '역사적 창의성은 시대적 환경의 영향을 받는다.',
      '팀 협업은 개인의 창의력을 억제할 수 있다.',
      '창의적인 아이디어는 문제 해결 능력에서 나온다.',
    ],
    answer: 2,
    explanation: `필자는 창의성이 고독한 천재의 산물이라는 통념을 반박하며 "the best environment for creativity is not isolation, but a rich network of diverse people and ideas"라고 결론짓는다. 정답은 ②이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 23번 글의 주제 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '글의 주제',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 23,
    passage: `The way animals communicate risk to each other has fascinated biologists for decades. Ground squirrels, for example, produce distinct alarm calls depending on whether the threat comes from the air or the ground. Meerkats coordinate sentinel duties, and their warning calls specify predator type with remarkable precision. What makes these systems even more interesting is evidence of learning: young animals that grow up in areas with fewer predators often fail to develop the full alarm repertoire of their species. This suggests that alarm communication is not purely instinctive but is partly shaped by social experience. Far from being simple reflexes, animal warning systems appear to be complex, learned, and socially transmitted — qualities we once considered uniquely human.`,
    question: '다음 글의 주제로 가장 적절한 것은?',
    options: [
      'the role of instinct in predator avoidance behavior',
      'the social learning dimension of animal alarm communication',
      'how predator diversity shapes animal migration patterns',
      'biological differences between aerial and ground predators',
      'the evolution of sentinel behavior in colonial mammals',
    ],
    answer: 2,
    explanation: `글의 핵심은 동물의 경보 신호가 순수한 본능이 아니라 사회적 학습을 통해 형성된다는 점이다("alarm communication is not purely instinctive but is partly shaped by social experience"). 정답은 ②이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 24번 글의 제목 [3점] ────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '글의 제목',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 24,
    passage: `Economists have long distinguished between goods that are rival — where one person's use diminishes availability for others — and those that are non-rival, like a radio broadcast, where one listener does not reduce another's access. Digital information sits firmly in the non-rival category: copying a file costs almost nothing and does not deplete the original. This property has profoundly disruptive implications. Industries built around scarcity — music, journalism, software — find their pricing power eroding when the marginal cost of reproduction approaches zero. The challenge for modern economies is not how to produce information, but how to sustain incentives for creating it when giving it away is nearly costless. Intellectual property law, subscription models, and platform ecosystems are all attempts to reintroduce artificial scarcity into an inherently abundant medium.`,
    question: '다음 글의 제목으로 가장 적절한 것은? [3점]',
    options: [
      'Why Scarcity Still Drives Innovation in the Digital Age',
      'The Hidden Costs of Free: Digital Piracy and Its Victims',
      'Reintroducing Scarcity: Economic Strategies for Non-Rival Goods',
      'How Subscription Models Transformed the Music Industry',
      'From Radio to Streaming: A History of Broadcast Economics',
    ],
    answer: 3,
    explanation: `글은 디지털 정보의 비경합적 특성으로 인한 경제적 과제와, 그에 대한 해결책(지식재산권, 구독 모델 등)으로 인위적 희소성을 재도입하는 시도를 다룬다. 정답은 ③이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 25번 도표 일치 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '도표 일치',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 25,
    passage: `The graph above shows the percentage of adults (aged 18–65) in five countries who reported reading at least one book per month in 2024. Among the five countries, Country A had the highest reading rate at 68%, while Country E had the lowest at 31%. Country B (54%) ranked second, followed by Country C (47%) and Country D (39%). The gap between Country A and Country B was 14 percentage points, which was the largest gap between any two consecutively ranked countries. Country D's reading rate was higher than Country E's by 8 percentage points.`,
    question: '다음 도표의 내용과 일치하지 않는 것은?',
    chartData: {
      type: 'bar',
      title: 'Percentage of Adults Reading at Least One Book Per Month (2024)',
      xAxis: ['Country A', 'Country B', 'Country C', 'Country D', 'Country E'],
      yAxis: 'Percentage (%)',
      values: [68, 54, 47, 39, 31],
    },
    options: [
      'Country A had the highest reading rate among all five countries.',
      'Country B ranked second with a reading rate of 54%.',
      'The gap between Country A and Country B was larger than between any other consecutively ranked countries.',
      'Country C\'s reading rate was higher than Country D\'s by 9 percentage points.',
      'Country E had the lowest reading rate at 31%.',
    ],
    answer: 4,
    explanation: `④ Country C(47%)와 Country D(39%)의 실제 차이는 8%p이지만 선택지에서 9%p로 잘못 제시하였으므로 일치하지 않는다. 정답은 ④이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 26번 인물 정보 불일치 ───────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '인물 정보 불일치',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 26,
    passage: `Elena Vasquez was born in 1978 in Buenos Aires, Argentina, and showed an early passion for marine biology. She earned her undergraduate degree from the University of Buenos Aires before moving to Scotland, where she completed her PhD at the University of Edinburgh in 2006. Her doctoral research focused on deep-sea bioluminescence. After graduating, she joined a research institute in Norway, where she spent seven years studying Arctic ocean ecosystems. She is the author of three widely used marine biology textbooks and has received the International Ocean Research Award twice, in 2015 and 2020. She currently serves as the director of the Pacific Marine Research Center in San Francisco, a position she has held since 2018.`,
    question: 'Elena Vasquez에 관한 다음 글의 내용과 일치하지 않는 것은?',
    options: [
      '1978년 아르헨티나 부에노스아이레스에서 태어났다.',
      '에든버러 대학교에서 박사 학위를 취득했다.',
      '박사 논문은 심해 생물발광을 주제로 했다.',
      '노르웨이 연구소에서 10년간 근무했다.',
      '국제 해양 연구상을 두 차례 수상했다.',
    ],
    answer: 4,
    explanation: `본문에서 노르웨이 연구소에서 "seven years" 근무했다고 했으나 ④번 선택지는 "10년간"이라고 하였다. 따라서 ④가 일치하지 않는다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 27번 안내문 불일치 ──────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '안내문 불일치',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 27,
    passage: `Greenfield Youth Photography Workshop

Open to participants aged 13–18
Dates: July 14–18, 2025 (Monday–Friday)
Time: 10:00 a.m. – 4:00 p.m. daily
Location: Greenfield Community Arts Center, Room 201
Instructor: Professional photographer Marcus Webb

Workshop highlights:
• Introduction to digital and film photography
• Outdoor shooting sessions each afternoon
• Final exhibition on the last day open to the public

Fee: $120 per participant (includes all materials)
Scholarships available — contact us for details

Registration deadline: June 30, 2025
To register, visit www.greenfieldarts.org or call (555) 204-7890

Note: Participants must bring their own camera (digital or film). Loaner cameras are not available.`,
    question: 'Greenfield Youth Photography Workshop에 관한 다음 안내문의 내용과 일치하지 않는 것은?',
    options: [
      '13세부터 18세까지 참가할 수 있다.',
      '워크숍은 5일간 진행된다.',
      '참가비에 모든 재료비가 포함된다.',
      '대여 카메라를 제공한다.',
      '마지막 날 일반에 공개되는 전시회가 열린다.',
    ],
    answer: 4,
    explanation: `안내문에 "Loaner cameras are not available"이라고 명시되어 있으므로 ④ "대여 카메라를 제공한다"는 내용과 일치하지 않는다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 28번 안내문 일치 ────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '안내문 일치',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 28,
    passage: `Riverside Book Fair 2025

Dates: September 6–7, 2025 (Saturday & Sunday)
Hours: 10:00 a.m. – 7:00 p.m.
Venue: Riverside Convention Hall, Main Floor

Highlights:
• Over 80 publishers and independent booksellers
• Author signing sessions scheduled throughout both days
• Children's reading corner with storytelling at 11:00 a.m. and 3:00 p.m. daily
• Free admission for children under 12

Admission: $8 per adult, $5 for students (with valid ID)
Group discounts available for parties of 10 or more

Parking: Free in Lot B; limited spaces in Lot A ($5/day)
For full schedule and author list, visit www.riversidebookfair.com`,
    question: 'Riverside Book Fair에 관한 다음 안내문의 내용과 일치하는 것은?',
    options: [
      '행사는 3일간 진행된다.',
      '어린이 스토리텔링은 하루에 한 번 진행된다.',
      '12세 미만 어린이는 무료로 입장할 수 있다.',
      '학생 입장료는 성인 입장료와 동일하다.',
      'Lot A 주차장은 무료이다.',
    ],
    answer: 3,
    explanation: `① 행사는 2일(토~일)이다. ② 스토리텔링은 11시, 3시로 하루 2회이다. ③ "Free admission for children under 12"로 일치한다. ④ 성인 $8, 학생 $5로 다르다. ⑤ Lot B가 무료이고 Lot A는 $5/day이다. 정답은 ③이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 29번 어법 ────────────────────────────────────────────────────────────
  {
    domain: QuestionDomain.GRAMMAR,
    subCategory: '어법',
    difficulty: 7,
    cefrLevel: 'B1 상',
    questionNumber: 29,
    passage: `Researchers studying collective behavior have found ①that a group of people acting together can reach decisions far more accurately than even the most knowledgeable individual member. This phenomenon, often called the "wisdom of crowds," depends on certain conditions ②being met: the members must make their judgments independently, without knowing what others think. When independence is ③violated — for instance, when people hear each other's opinions before deciding — the crowd's estimate tends to mirror the first ④spoke voice rather than averaging genuine individual knowledge. The result is not wisdom but social contagion, a cascade of influenced opinions ⑤masquerading as collective intelligence.`,
    question: '다음 글의 밑줄 친 부분 중, 어법상 틀린 것은?',
    underlines: ['①that', '②being met', '③violated', '④spoke', '⑤masquerading'],
    options: ['①', '②', '③', '④', '⑤'],
    answer: 4,
    explanation: `④ "spoke"는 명사 voice를 수식하는 분사 자리이다. 과거형 동사 spoke가 아니라 과거분사 "spoken"(발화된)으로 고쳐야 한다("the first spoken voice"). 나머지는 모두 어법상 올바르다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 30번 어휘 [3점] ──────────────────────────────────────────────────────
  {
    domain: QuestionDomain.VOCABULARY,
    subCategory: '어휘',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 30,
    passage: `The concept of "deep reading" refers to the slow, ①immersive engagement with a text that allows readers to draw inferences, build analogies, and experience what some neuroscientists call a "reading trance." This kind of reading is ②distinct from the skimming and scanning we typically do online, where the goal is to extract information quickly. Deep reading requires the reader to remain with a text long enough for meaning to ③accumulate — to let early passages reshape the interpretation of later ones. Critics worry that habitual screen reading is ④reinforcing the neural circuits associated with patience and sustained attention, leaving us less capable of the very cognitive depth that literary culture has long ⑤prized.`,
    question: '다음 글의 밑줄 친 부분 중, 문맥상 낱말의 쓰임이 적절하지 않은 것은? [3점]',
    underlines: ['①immersive', '②distinct', '③accumulate', '④reinforcing', '⑤prized'],
    options: ['①', '②', '③', '④', '⑤'],
    answer: 4,
    explanation: `④ "reinforcing"은 '강화하다'는 의미이다. 화면 읽기가 인내와 지속적 주의에 관련된 신경 회로를 약화시킨다는 내용이어야 자연스럽다. "reinforcing" 대신 "undermining"(약화시키다)이 적절하다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 31번 빈칸 단어 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '빈칸',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 31,
    passage: `Laboratory studies of problem-solving often find that the best solutions emerge not during concentrated effort, but during periods of deliberate rest. When people step away from a difficult problem and allow their minds to wander freely, a process of unconscious recombination appears to occur, linking concepts that focused attention would never have joined. This is why many creative professionals report their most valuable insights arriving in the shower, during a walk, or just before sleep. The implication is that __________ may be as important a cognitive tool as focused concentration, and that designing work environments that include it is not a concession to laziness but an investment in productive thinking.`,
    question: '다음 빈칸에 들어갈 말로 가장 적절한 것은?',
    options: [
      'competition',
      'distraction',
      'incubation',
      'memorization',
      'repetition',
    ],
    answer: 3,
    explanation: `글은 집중적 노력이 아닌 휴식 중 무의식적 재결합을 통해 좋은 해결책이 나온다고 설명한다. 이는 심리학에서 '부화 단계(incubation)'로 알려진 현상이다. 빈칸에는 ③ incubation이 가장 적절하다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 32번 빈칸 구 [3점] ──────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '빈칸',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 32,
    passage: `One of the most persistent misunderstandings in science communication is the belief that simply presenting accurate facts will change people's minds. Decades of research in social psychology tell a different story. When a fact contradicts a person's existing worldview, the mind does not evaluate it neutrally; instead, it enlists motivated reasoning to discredit the source, reinterpret the data, or generate counterarguments. This means that __________ is often the more critical variable in whether new information is accepted — not the logical strength of the evidence, but whether the audience perceives the communicator as sharing their values and understanding their concerns.`,
    question: '다음 빈칸에 들어갈 말로 가장 적절한 것은? [3점]',
    options: [
      'the complexity of the scientific data',
      "the communicator's perceived cultural alignment with the audience",
      'the frequency with which information is repeated',
      'the academic credentials of the researcher',
      'whether the information supports current policy',
    ],
    answer: 2,
    explanation: `글의 핵심은 사실 자체보다 청중이 커뮤니케이터를 자신과 같은 가치관을 가진 사람으로 인식하는지가 중요하다는 것이다. 빈칸에는 ②가 가장 적절하다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 33번 빈칸 구 ─────────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '빈칸',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 33,
    passage: `Historians of technology have noted a paradox in the adoption of labor-saving devices. One would expect that a tool designed to reduce the time needed for a task would ultimately free up more leisure. Yet time-use surveys consistently show that as household technology improves, the time people spend on domestic work does not decline proportionally. The introduction of the washing machine, for instance, was followed not by fewer hours of laundry but by higher standards of cleanliness — people washed their clothes more frequently because it had become easier. This suggests that __________: the moment a task becomes easier, expectations about how often or how thoroughly it should be performed tend to rise.`,
    question: '다음 빈칸에 들어갈 말로 가장 적절한 것은?',
    options: [
      'convenience creates its own demand',
      'technology cannot replace human judgment',
      'domestic work is undervalued in modern economies',
      'labor-saving devices increase productivity in workplaces',
      'leisure time depends more on income than on technology',
    ],
    answer: 1,
    explanation: `세탁기 도입 후 세탁 빈도가 오히려 증가한 사례는 '편리함이 스스로 수요를 만든다'는 것을 보여준다. 정답은 ① "convenience creates its own demand"이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 34번 빈칸 구 [3점] ──────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '빈칸',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 34,
    passage: `Classical economic models assume that individuals act to maximize their own utility, where utility is understood as personal gain or preference satisfaction. But decades of experimental economics have revealed systematic deviations from this prediction. In ultimatum game experiments, participants routinely reject offers that are technically profitable because they perceive them as unfair. They sacrifice real money to punish perceived injustice, even when they will never interact with their counterpart again. This behavior is puzzling if we accept that humans are purely self-interested calculators, but it makes perfect sense if we recognize that __________. Humans evolved in small, interdependent groups where maintaining norms of fairness was essential to long-term cooperation and collective survival.`,
    question: '다음 빈칸에 들어갈 말로 가장 적절한 것은? [3점]',
    options: [
      'financial incentives are insufficient to motivate behavior change',
      'economic rationality breaks down under conditions of uncertainty',
      'the enforcement of fairness norms is itself a form of utility',
      'repeated interactions are necessary for trust to develop',
      'cooperation requires a central authority to coordinate decisions',
    ],
    answer: 3,
    explanation: `금전적 손해를 감수하면서까지 불공정한 제안을 거부하는 행동은, 공정성 규범의 집행 자체가 인간에게 효용(utility)의 한 형태임을 시사한다. 정답은 ③이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 35번 무관 문장 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '무관 문장',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 35,
    passage: `Biomimicry — the practice of drawing engineering solutions from nature — has produced some remarkable innovations. ① The structure of a lotus leaf, which repels water and dirt through microscopic surface patterns, inspired the development of self-cleaning coatings now used on buildings and fabrics. ② Termite mounds, which maintain stable internal temperatures despite extreme external heat, have guided the design of energy-efficient ventilation systems in modern architecture. ③ The study of termite behavior has also contributed significantly to advances in robotics and swarm intelligence algorithms. ④ The hook-and-loop fasteners we know as Velcro were invented after an engineer noticed how burr seeds clung to his dog's fur. ⑤ Increasingly, companies working in materials science and structural engineering actively scan biological literature for mechanisms they can adapt.`,
    question: '다음 글에서 전체 흐름과 관계없는 문장은?',
    options: ['①', '②', '③', '④', '⑤'],
    answer: 3,
    explanation: `전체 글은 자연에서 착안한 공학적 혁신(생체모방)을 다루고 있다. ③번은 흰개미 행동 연구가 로봇공학과 군집 지능에 기여했다는 내용으로, 생체모방 공학 혁신과 직접 연결되지 않는 이탈된 문장이다. 정답은 ③이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 36번 글의 순서 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '글의 순서',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 36,
    passage: `For centuries, the ocean floor was assumed to be a featureless desert — dark, cold, and nearly lifeless.

(A) Yet when deep-sea exploration began in earnest in the twentieth century, scientists discovered an astonishing variety of life thriving around hydrothermal vents, where superheated water rich in minerals erupts from the seafloor.

(B) These communities drew their energy not from sunlight but from chemical reactions — a process called chemosynthesis — fundamentally challenging the assumption that all life on Earth depends on solar energy.

(C) This discovery forced a revision of one of biology's most basic principles: that photosynthesis, and therefore sunlight, is the foundation of virtually every food chain.`,
    question: '주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?',
    introPassage: `For centuries, the ocean floor was assumed to be a featureless desert — dark, cold, and nearly lifeless.`,
    paragraphs: {
      A: `Yet when deep-sea exploration began in earnest in the twentieth century, scientists discovered an astonishing variety of life thriving around hydrothermal vents, where superheated water rich in minerals erupts from the seafloor.`,
      B: `These communities drew their energy not from sunlight but from chemical reactions — a process called chemosynthesis — fundamentally challenging the assumption that all life on Earth depends on solar energy.`,
      C: `This discovery forced a revision of one of biology's most basic principles: that photosynthesis, and therefore sunlight, is the foundation of virtually every food chain.`,
    },
    options: [
      '(A) – (B) – (C)',
      '(A) – (C) – (B)',
      '(B) – (A) – (C)',
      '(C) – (A) – (B)',
      '(C) – (B) – (A)',
    ],
    answer: 1,
    explanation: `주어진 문장은 해저가 생명이 없다는 가정을 소개한다. (A)에서 심해 탐사로 열수분출공 생물 발견을 서술하고, (B)에서 이들이 화학합성으로 에너지를 얻는다고 설명하며, (C)에서 이 발견이 생물학적 원칙을 수정하게 했다고 결론짓는다. 정답은 ① (A)-(B)-(C)이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 37번 글의 순서 [3점] ────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '글의 순서',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 37,
    passage: `The placebo effect is often dismissed as a curiosity — a reminder that some patients improve simply because they believe they are being treated.

(A) What is even more surprising is the "open-label placebo" phenomenon: patients who are explicitly told they are receiving a sugar pill with no active ingredient still show measurable improvement. This suggests that the ritual of medical care itself triggers genuine physiological responses.

(B) Research in psychoneuroimmunology has shown that expectation alone can trigger the release of endorphins, alter immune function, and even modulate pain perception through changes in brain activity.

(C) Rather than being a sign that a treatment is ineffective, the placebo response reflects how deeply the mind shapes bodily experience — a connection that conventional medicine has historically undervalued.`,
    question: '주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은? [3점]',
    introPassage: `The placebo effect is often dismissed as a curiosity — a reminder that some patients improve simply because they believe they are being treated.`,
    paragraphs: {
      A: `What is even more surprising is the "open-label placebo" phenomenon: patients who are explicitly told they are receiving a sugar pill with no active ingredient still show measurable improvement. This suggests that the ritual of medical care itself triggers genuine physiological responses.`,
      B: `Research in psychoneuroimmunology has shown that expectation alone can trigger the release of endorphins, alter immune function, and even modulate pain perception through changes in brain activity.`,
      C: `Rather than being a sign that a treatment is ineffective, the placebo response reflects how deeply the mind shapes bodily experience — a connection that conventional medicine has historically undervalued.`,
    },
    options: [
      '(A) – (B) – (C)',
      '(A) – (C) – (B)',
      '(B) – (A) – (C)',
      '(B) – (C) – (A)',
      '(C) – (A) – (B)',
    ],
    answer: 3,
    explanation: `주어진 문장에서 위약 효과를 소개한다. (B)에서 기대만으로도 실제 신체 반응이 일어남을 과학적으로 설명하고, (A)에서 공개 위약 현상으로 이를 심화시킨 후, (C)에서 마음과 신체의 연결이라는 더 큰 의미로 결론짓는다. 정답은 ③ (B)-(A)-(C)이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 38번 문장 삽입 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '문장 삽입',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 38,
    passage: `Modern industrial agriculture has dramatically increased food production over the past century. ① Advances in fertilizers, pesticides, and high-yield crop varieties have allowed farmers to produce more calories per acre than at any point in human history. ② Large-scale monocultures — fields devoted entirely to a single crop — have become the dominant model, prized for their ease of mechanization and harvest predictability. ③ When a single variety covers vast areas, a single pathogen or pest can devastate entire harvests, as the Irish potato famine grimly illustrated. ④ Traditional polyculture farming systems, by contrast, maintained natural pest control through diversity, reducing the risk of catastrophic failure. ⑤ The challenge for contemporary agriculture is to find ways of retaining productive efficiency while rebuilding the ecological complexity that monocultures have stripped away.`,
    question: '글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은?',
    insertSentence: `However, this apparent efficiency comes at a significant cost to biodiversity.`,
    options: ['①', '②', '③', '④', '⑤'],
    answer: 2,
    explanation: `주어진 문장 "this apparent efficiency comes at a significant cost to biodiversity"는 단일 재배의 효율성을 언급한 ② 다음에 위치해야 한다. ② 뒤에 삽입하면 단일 재배의 효율성 뒤에 이어지는 생물 다양성 비용을 지적하고, ③의 병충해 위험 설명으로 자연스럽게 연결된다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 39번 문장 삽입 [3점] ────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '문장 삽입',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 39,
    passage: `Behavioral economists have documented a robust finding known as loss aversion. ① People feel the pain of losing a given sum of money roughly twice as intensely as they feel the pleasure of gaining the same amount. ② This means that in evaluating a potential trade or bet, individuals weigh potential losses far more heavily than equivalent gains. ③ For example, a person offered a 50/50 gamble — win $100 or lose $100 — will typically refuse, even though the expected value is zero and a fully rational actor would be indifferent. ④ Because negative outcomes loom so much larger psychologically than positive ones, people often forgo objectively beneficial opportunities to avoid the prospect of any loss. ⑤ Designers of savings and investment products have learned to frame choices in terms of avoiding loss rather than achieving gain, since this framing reliably increases participation.`,
    question: '글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은? [3점]',
    insertSentence: `This asymmetry explains why loss aversion tends to dominate rational calculation in everyday financial decisions.`,
    options: ['①', '②', '③', '④', '⑤'],
    answer: 4,
    explanation: `주어진 문장의 "This asymmetry"는 손실이 이익보다 두 배 강하게 느껴진다는 비대칭을 가리킨다. ④ 앞까지 그 비대칭의 구체적 예시(도박 거부)가 제시되고, ④ 뒤에서는 일상 금융 결정에서의 결과를 설명하므로 ④가 적절한 위치이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 40번 요약 완성 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '요약 완성',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 40,
    passage: `Research on expert performance consistently finds that what distinguishes top performers from average ones is not raw talent or intelligence but the quality of their practice. Ordinary practice — simply repeating a task — produces limited improvement beyond a basic level of competence. Expert-level skill requires what psychologists call "deliberate practice": highly focused effort directed at specific weaknesses, with immediate and accurate feedback. A pianist who plays through a piece from start to finish, smoothing over trouble spots, makes far slower progress than one who isolates the difficult passage and attacks it repeatedly with conscious attention to errors. The key is operating at the edge of current ability, not within the comfortable zone of things already mastered.`,
    question: '다음 글의 내용을 한 문장으로 요약하고자 한다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?',
    summary: `Achieving expert-level performance requires (A) __________ practice focused on specific weaknesses, rather than repeating tasks within one's (B) __________ ability zone.`,
    options: [
      { A: 'deliberate', B: 'comfortable' },
      { A: 'frequent', B: 'current' },
      { A: 'deliberate', B: 'advanced' },
      { A: 'competitive', B: 'comfortable' },
      { A: 'frequent', B: 'limited' },
    ],
    answer: 1,
    explanation: `본문의 핵심어는 "deliberate practice"와 "the comfortable zone of things already mastered"이다. 요약문의 (A)에는 deliberate, (B)에는 comfortable이 가장 적절하다. 정답은 ①이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 41번 장문 제목 [3점] ────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '장문 제목',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 41,
    linkedPassage: 'suneung2026_long1',
    passage: LONG_PASSAGE_1,
    question: '다음 글의 제목으로 가장 적절한 것은? [3점]',
    options: [
      'Why Digital Advertising Needs Stronger Regulation',
      'The Illusion of Consent: Power and Informational Autonomy in the Digital Age',
      'How Big Data Is Transforming the Global Insurance Industry',
      'Privacy vs. Convenience: Finding the Right Balance Online',
      'The Economics of Free: How Platforms Monetize User Data',
    ],
    answer: 2,
    explanation: `지문 전체는 디지털 시대에 개인 정보 자율권이 얼마나 환상에 불과한지를 다루며, 동의의 허구성과 권력 비대칭을 지적한다. 가장 적합한 제목은 ② "The Illusion of Consent: Power and Informational Autonomy in the Digital Age"이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 42번 장문 어휘 ───────────────────────────────────────────────────────
  {
    domain: QuestionDomain.VOCABULARY,
    subCategory: '어휘',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 42,
    linkedPassage: 'suneung2026_long1',
    passage: LONG_PASSAGE_1_ANNOTATED,
    question: '밑줄 친 (a)~(e) 중에서 문맥상 낱말의 쓰임이 적절하지 않은 것은?',
    underlines: ['(a)byproduct', '(b)dramatically', '(c)granularity', '(d)uncanny', '(e)strengths'],
    options: ['(a)', '(b)', '(c)', '(d)', '(e)'],
    answer: 5,
    explanation: `(e) "strengths"(강점)는 문맥상 부적절하다. 정치적 마이크로타게팅이 개인의 특정 심리적 '취약점(vulnerabilities)'을 이용하는 것이므로 "vulnerabilities"로 교체해야 한다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 43번 장문 독해 순서 ──────────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '장문 독해',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 43,
    linkedPassage: 'suneung2026_long2',
    passage: LONG_PASSAGE_2,
    question: '주어진 글 (A)에 이어질 내용을 순서에 맞게 배열한 것으로 가장 적절한 것은?',
    options: [
      '(B) – (C) – (D)',
      '(B) – (D) – (C)',
      '(C) – (B) – (D)',
      '(C) – (D) – (B)',
      '(D) – (B) – (C)',
    ],
    answer: 1,
    explanation: `(A)에서 Nora가 잠긴 센터를 발견하는 문제 상황이 제시된다. (B)에서 갈등의 원인(기부금 분쟁)을 알게 되고 좌절감을 느낀다. (C)에서 Yoon 씨를 찾아가 설득하여 센터가 열린다. (D)에서 화해한 가족들이 함께 일하는 모습을 보며 교훈을 얻는다. 정답은 ① (B)-(C)-(D)이다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 44번 장문 독해 심경 변화 ────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '장문 독해',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 44,
    linkedPassage: 'suneung2026_long2',
    passage: LONG_PASSAGE_2,
    question: '윗글에 드러난 Nora의 심경 변화로 가장 적절한 것은?',
    options: [
      '기대감 → 당혹감 → 보람',
      '분노 → 체념 → 안도',
      '좌절 → 결단 → 깨달음',
      '설렘 → 실망 → 분노',
      '무관심 → 호기심 → 감동',
    ],
    answer: 3,
    explanation: `Nora는 센터가 잠겨 있음을 발견하고 좌절(frustration)하고, Yoon 씨를 찾아가는 결단을 내리며, 마지막에 공동체에 대한 깨달음을 얻는다. 심경 변화는 ③ 좌절 → 결단 → 깨달음이 가장 적절하다.\n\n${SOURCE_LABEL}`,
  },

  // ─── 45번 장문 독해 내용 일치 ────────────────────────────────────────────
  {
    domain: QuestionDomain.READING,
    subCategory: '장문 독해',
    difficulty: 8,
    cefrLevel: 'B2 하',
    questionNumber: 45,
    linkedPassage: 'suneung2026_long2',
    passage: LONG_PASSAGE_2,
    question: '윗글의 내용과 일치하는 것은?',
    options: [
      'Nora는 이 마을에서 처음 봉사 활동을 시작했다.',
      '지역 센터는 화재로 인해 폐쇄되었다.',
      'Nora는 학회 초청을 거절하고 마을에 왔다.',
      'Yoon 씨는 Nora의 방문을 처음부터 환영했다.',
      '이틀 후에야 센터가 다시 문을 열었다.',
    ],
    answer: 3,
    explanation: `본문에서 Nora는 "turned down a lucrative conference invitation"(수익성 있는 학회 초청을 거절하고)이라고 명시되어 있다. 정답은 ③이다. ① 첫 방문이 아니라 레지던트 수료 후 돌아온 것, ② 기부금 분쟁으로 폐쇄, ④ Yoon씨는 "warily(경계하며)" 문을 열었음, ⑤ 다음날 아침에 열렸다.\n\n${SOURCE_LABEL}`,
  },
]

async function main() {
  console.log('기존 suneung2026 데이터 삭제 중...')

  // 기존 등록된 suneung2026 문제 전체 삭제 후 재등록
  const existing = await prisma.question.findMany({
    where: {
      academyId: null,
      contentJson: {
        path: ['grade'],
        equals: 'suneung2026',
      },
    },
    select: { id: true },
  })

  if (existing.length > 0) {
    await prisma.question.deleteMany({
      where: {
        id: { in: existing.map((q) => q.id) },
      },
    })
    console.log(`  → ${existing.length}개 삭제 완료\n`)
  } else {
    console.log('  → 삭제할 기존 데이터 없음\n')
  }

  console.log('2026 수능 영어 영역 유사문제 시드 데이터 등록 시작...')
  console.log(`총 ${questions.length}개 문제 처리 예정\n`)

  let created = 0

  for (const q of questions) {
    type QuestionObj = typeof q & Record<string, unknown>
    const qr = q as QuestionObj

    // correct_answer: 번호(1~5) → 알파벳 A~E 변환
    const letters = ['A', 'B', 'C', 'D', 'E']
    const correctAnswer = letters[(q.answer as number) - 1] ?? 'A'

    const contentJson: Record<string, unknown> = {
      type: 'multiple_choice',
      questionNumber: q.questionNumber,
      grade: 'suneung2026',
      passage: q.passage,
      question_text: q.question,
      options: q.options,
      correct_answer: correctAnswer,
      explanation: q.explanation,
    }

    // 문제 유형별 추가 필드
    if (qr.underline) contentJson.underline = qr.underline
    if (qr.underlines) contentJson.underlines = qr.underlines
    if (qr.insertSentence) contentJson.insertSentence = qr.insertSentence
    if (qr.introPassage) contentJson.introPassage = qr.introPassage
    if (qr.paragraphs) contentJson.paragraphs = qr.paragraphs
    if (qr.chartData) contentJson.chartData = qr.chartData
    if (qr.summary) contentJson.summary = qr.summary
    if (qr.linkedPassage) contentJson.linkedPassage = qr.linkedPassage

    await prisma.question.create({
      data: {
        domain: q.domain,
        subCategory: q.subCategory,
        difficulty: q.difficulty,
        cefrLevel: q.cefrLevel,
        source: QuestionSource.SYSTEM,
        isVerified: true,
        isActive: true,
        academyId: null,
        contentJson,
        statsJson: { timesUsed: 0, avgScore: null },
      },
    })

    console.log(`✅  ${q.questionNumber}번 (${q.subCategory}) — 등록 완료`)
    created++
  }

  console.log(`\n───────────────────────────────`)
  console.log(`완료: ${created}개 생성`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
